### PR TITLE
Added support for Markdown files

### PR DESCRIPTION
**Pull request by RichNSD**
All I did was copy the code defining HTML comments and use it for Markdown, then I updated the supported languages.

### CODE REVIEW

**Comment by coswat** [comment]
can u update the comment

**Comment by RichNSD** [comment]
@coswat Update which comment with what information?

**Comment by coswat** [comment]
in 60th line, the comment shows html instead of md

**Comment by RichNSD** [comment]
@coswat Oh I see what you're saying. Yeah I'll fix that.

**Review by RichNSD — COMMENTED** [review]
Comment fixed

**Pull request merged**
